# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "site"

# This page should be the root of your website. It's important.
page = "https://simone-santoni.notion.site/SMM694-256412a433f14d8bbd91c53072903ce1"
